Adding TS typings.
sindresorhus/shell-env pull request #13
Opened 2018-10-21 02:42 UTC by Fazendaaa

Hey, @sindresorhus.

Due to Hacktoberfest 2018, I'm contributing to some packages.

TypeScript typings help a lot of us who use it due to it's integration to TSLint and some more strict checkings, needed to be performed in some cases in the used packages as well; that's why I've decided to share the ones that I've made, making it more accessible to all programmers in this environment :)

Besides adding this, I would love to add a Husky integration to perform linter checkings, tests and documentation to git hooks. While doing this, if is it of your interest I can rewrite the JS parts in TS also, adding tests and everything.

2018-10-21 07:18 UTC, sindresorhus commented
Hey. Awesome to see participation for Hacktoberfest. ✨

Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

2018-10-21 07:19 UTC, sindresorhus commented
> Besides adding this, I would love to add a Husky integration to perform linter checkings, tests and documentation to git hooks. While doing this, if is it of your interest I can rewrite the JS parts in TS also, adding tests and everything.

I appreciate the offer, but I'm not interested in that.

2018-10-21 11:33 UTC, Fazendaaa commented
> Hey. Awesome to see participation for Hacktoberfest. sparkles
> 
> Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

No problems :)

2018-10-24 01:51 UTC, Fazendaaa commented
@sindresorhus what awesome guideline for contributions, I did not know these standards of yours and the first time I see something like that. I learned a lot.

2018-10-24 03:07 UTC, sindresorhus commented
> For packages with a default export, use export default foo;, not export = foo;. You will have to add module.exports.default = foo; to the index.js file.

> The pull request should have the title Add TypeScript definition. (Copy-paste it so you don't get it wrong)

2018-10-24 03:09 UTC, sindresorhus requested changes

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> +    readonly TERM_PROGRAM: string;
These are no guaranteed to exist.

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> +export interface ShellEnv {
```suggestion
export interface EnvironmentVariables {
```

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> +    readonly [x: string]: string;
```suggestion
    readonly [key: string]: string;
```

2018-10-24 03:09 UTC, sindresorhus commented on package.json
> +		]
This is not needed.

2018-10-24 03:09 UTC, sindresorhus commented on index.test-d.ts
> +(async () => {
> tsd-check supports top-level await. - https://github.com/sindresorhus/typescript-definition-style-guide

2018-10-24 03:09 UTC, sindresorhus commented on index.test-d.ts
> +import shellEnv, { sync, ShellEnv } from '.';
```suggestion
import shellEnv, {sync, ShellEnv} from '.';
```

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> +export function shellEnv(shell?: string): Promise<ShellEnv>;
This should be a default export only, not a named export too.

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> + * @param shell To read the environment variables from.
> There's a dash after the parameter name. - https://github.com/sindresorhus/typescript-definition-style-guide

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> + * @param shell To read the environment variables from.
```suggestion
 * @param shell - The shell to read the environment variables from.
```

2018-10-24 03:09 UTC, sindresorhus commented on index.d.ts
> + * @param shell To read the environment variables from.
Document the default value.

2018-10-24 10:48 UTC, Fazendaaa commented on package.json
> +		]
Okay

2018-10-24 10:52 UTC, Fazendaaa commented on index.d.ts
> +    readonly TERM_PROGRAM: string;
Thanks

2019-02-01 05:11 UTC, sindresorhus approved these changes

2019-02-01 05:11 UTC, merged

2019-02-01 05:11 UTC, sindresorhus commented
Nice work! :)